[2022-09-17 19:34:29,285: INFO: stage_01_get_data]: 
********************
[2022-09-17 19:34:29,285: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-09-17 19:34:29,290: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-17 19:34:29,290: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-17 19:34:29,290: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME completed!<<<<<

[2022-09-17 22:31:05,481: INFO: stage_01_get_data]: 
********************
[2022-09-17 22:31:05,481: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-09-17 22:31:05,483: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-17 22:31:05,483: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-17 22:31:05,483: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME completed!<<<<<

[2022-09-17 22:31:17,725: INFO: stage_01_get_data]: 
********************
[2022-09-17 22:31:17,725: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-09-17 22:31:17,725: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-17 22:31:17,730: INFO: common]: created directory at: data
[2022-09-17 22:31:17,730: INFO: stage_01_get_data]: downloading started...
[2022-09-17 22:31:18,329: ERROR: stage_01_get_data]: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 59, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_get_data.py", line 35, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
[2022-09-18 11:49:23,759: INFO: stage_01_get_data]: 
********************
[2022-09-18 11:49:23,759: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-09-18 11:49:23,765: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 11:49:23,766: INFO: common]: created directory at: data
[2022-09-18 11:49:23,766: INFO: stage_01_get_data]: downloading started...
[2022-09-18 11:49:23,768: ERROR: stage_01_get_data]: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 50, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 34, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2022-09-18 11:50:02,222: INFO: stage_01_get_data]: 
********************
[2022-09-18 11:50:02,222: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-09-18 11:50:02,225: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 11:50:02,229: INFO: common]: created directory at: data
[2022-09-18 11:50:02,229: INFO: stage_01_get_data]: downloading started...
[2022-09-18 11:50:02,232: ERROR: stage_01_get_data]: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 50, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 34, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2022-09-18 12:02:45,568: INFO: stage_01_get_data]: 
********************
[2022-09-18 12:02:45,568: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-09-18 12:02:45,572: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 12:02:45,572: INFO: common]: created directory at: data
[2022-09-18 12:02:45,572: INFO: stage_01_get_data]: downloading started...
[2022-09-18 12:02:45,572: ERROR: stage_01_get_data]: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 49, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 33, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2022-09-18 12:03:18,782: INFO: stage_01_get_data]: 
********************
[2022-09-18 12:03:18,783: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-09-18 12:03:18,785: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 12:03:18,786: INFO: common]: created directory at: data
[2022-09-18 12:03:18,786: INFO: stage_01_get_data]: downloading started...
[2022-09-18 12:03:18,786: ERROR: stage_01_get_data]: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 49, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 33, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2022-09-18 13:00:11,387: INFO: stage_01_get_data]: 
********************
[2022-09-18 13:00:11,389: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-18 13:00:11,391: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 13:00:11,392: INFO: common]: created directory at: data
[2022-09-18 13:00:11,392: INFO: stage_01_get_data]: downloading started...
[2022-09-18 13:00:11,393: ERROR: stage_01_get_data]: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 48, in <module>
    main(config_path=parsed_args.config)
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 33, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2022-09-18 13:07:09,264: INFO: stage_01_get_data]: 
********************
[2022-09-18 13:07:09,268: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-18 13:07:09,270: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 13:07:09,278: INFO: common]: created directory at: data
[2022-09-18 13:07:09,278: INFO: stage_01_get_data]: downloading started...
[2022-09-18 13:07:09,284: ERROR: stage_01_get_data]: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 49, in <module>
    main(config_path=parsed_args.config)
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 34, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2022-09-18 13:19:06,097: INFO: stage_01_get_data]: 
********************
[2022-09-18 13:19:06,097: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-18 13:19:06,098: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 13:19:06,179: INFO: common]: created directory at: data
[2022-09-18 13:19:06,180: INFO: stage_01_get_data]: downloading started...
[2022-09-18 13:19:06,182: ERROR: stage_01_get_data]: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 49, in <module>
    main(config_path=parsed_args.config)
  File "c:/Users/aakas/Documents/projects/computer vision/MLflow-classifire-CNN/src/stage_01_get_data.py", line 34, in main
    filename, headers = req.urlretrieve(URL, data_file_path)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2022-09-18 13:22:21,436: INFO: stage_01_get_data]: 
********************
[2022-09-18 13:22:21,436: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-18 13:22:21,436: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-18 13:22:21,589: INFO: common]: created directory at: data
[2022-09-18 13:22:21,589: INFO: stage_01_get_data]: downloading started...
[2022-09-18 13:23:29,641: INFO: stage_01_get_data]: filename:data\data.zip created with info 
Content-Type: application/octet-stream
Accept-Ranges: bytes
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-blob-content-md5: 4TekUHNw2UJGm20meiTqBA==
Last-Modified: Mon, 09 May 2022 20:42:07 GMT
ETag: "0x8DA31FC621E01C4"
Content-Length: 824887076
Date: Sun, 18 Sep 2022 07:52:20 GMT
Connection: close


[2022-09-18 13:23:29,641: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2022-09-19 06:19:19,232: INFO: stage_01_get_data]: 
********************
[2022-09-19 06:19:19,232: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-19 06:19:19,239: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 06:19:19,244: INFO: common]: created directory at: data
[2022-09-19 06:19:19,245: INFO: stage_01_get_data]: filename:data.zip already present
[2022-09-19 06:19:19,245: INFO: stage_01_get_data]: data already extracted
[2022-09-19 06:19:19,246: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2022-09-19 06:20:13,818: INFO: stage_01_get_data]: 
********************
[2022-09-19 06:20:13,818: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-19 06:20:13,818: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 06:20:13,823: INFO: common]: created directory at: data
[2022-09-19 06:20:13,823: INFO: stage_01_get_data]: filename:data.zip already present
[2022-09-19 06:20:13,824: INFO: stage_01_get_data]: data already extracted
[2022-09-19 06:20:13,824: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2022-09-19 06:21:56,463: INFO: stage_01_get_data]: 
********************
[2022-09-19 06:21:56,463: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-19 06:21:56,469: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 06:21:56,471: INFO: common]: created directory at: data
[2022-09-19 06:21:56,471: INFO: stage_01_get_data]: filename:data.zip already present
[2022-09-19 06:21:56,471: INFO: stage_01_get_data]: data already extracted
[2022-09-19 06:21:56,471: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2022-09-19 06:23:22,652: INFO: stage_01_get_data]: 
********************
[2022-09-19 06:23:22,652: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-19 06:23:22,657: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 06:23:22,657: INFO: common]: created directory at: data
[2022-09-19 06:23:22,657: INFO: stage_01_get_data]: filename:data.zip already present
[2022-09-19 06:23:22,657: INFO: stage_01_get_data]: data already extracted
[2022-09-19 06:23:22,657: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2022-09-19 06:36:21,623: INFO: stage_01_get_data]: 
********************
[2022-09-19 06:36:21,623: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-19 06:36:21,628: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 06:36:21,628: INFO: common]: created directory at: data
[2022-09-19 06:36:21,628: INFO: stage_01_get_data]: filename:data.zip already present
[2022-09-19 06:36:21,628: INFO: common]: created directory at: data
[2022-09-19 06:36:21,628: INFO: common]: extraction started...
[2022-09-19 06:48:39,303: INFO: common]: extracted data\data.zip to data
[2022-09-19 06:48:39,316: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2022-09-19 07:05:54,612: INFO: stage_01_get_data]: 
********************
[2022-09-19 07:05:54,612: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2022-09-19 07:05:54,617: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 07:05:54,617: INFO: common]: created directory at: data
[2022-09-19 07:05:54,617: INFO: stage_01_get_data]: filename:data.zip already present
[2022-09-19 07:05:54,617: INFO: stage_01_get_data]: data already extracted
[2022-09-19 07:05:54,620: INFO: common]: created directory at: data\bad_data
[2022-09-19 07:05:54,819: INFO: data_management]: data\PetImages\Cat\10073.jpg not of expected format
[2022-09-19 07:05:54,908: INFO: data_management]: data\PetImages\Cat\10125.jpg not of expected format
[2022-09-19 07:05:55,776: INFO: data_management]: data\PetImages\Cat\10404.jpg not of expected format
[2022-09-19 07:05:56,008: INFO: data_management]: data\PetImages\Cat\10501.jpg not of expected format
[2022-09-19 07:05:56,606: INFO: data_management]: data\PetImages\Cat\10820.jpg not of expected format
[2022-09-19 07:05:56,732: INFO: data_management]: data\PetImages\Cat\10874.jpg not of expected format
[2022-09-19 07:05:57,122: INFO: data_management]: data\PetImages\Cat\11083.jpg not of expected format
[2022-09-19 07:05:57,128: INFO: data_management]: data\PetImages\Cat\11086.jpg not of expected format
[2022-09-19 07:05:57,143: INFO: data_management]: data\PetImages\Cat\11091.jpg not of expected format
[2022-09-19 07:05:57,151: INFO: data_management]: data\PetImages\Cat\11095.jpg not of expected format
[2022-09-19 07:05:57,363: INFO: data_management]: data\PetImages\Cat\11196.jpg not of expected format
[2022-09-19 07:05:57,391: INFO: data_management]: data\PetImages\Cat\11210.jpg not of expected format
[2022-09-19 07:05:57,698: INFO: data_management]: data\PetImages\Cat\11397.jpg not of expected format
[2022-09-19 07:05:57,922: INFO: data_management]: data\PetImages\Cat\1151.jpg not of expected format
[2022-09-19 07:05:58,017: INFO: data_management]: data\PetImages\Cat\11565.jpg not of expected format
[2022-09-19 07:05:58,086: INFO: data_management]: data\PetImages\Cat\11602.jpg not of expected format
[2022-09-19 07:05:58,320: INFO: data_management]: data\PetImages\Cat\11729.jpg not of expected format
[2022-09-19 07:05:58,596: INFO: data_management]: data\PetImages\Cat\11864.jpg not of expected format
[2022-09-19 07:05:58,614: INFO: data_management]: data\PetImages\Cat\11874.jpg not of expected format
[2022-09-19 07:05:58,921: INFO: data_management]: data\PetImages\Cat\11935.jpg not of expected format
[2022-09-19 07:05:59,187: INFO: data_management]: data\PetImages\Cat\12080.jpg not of expected format
[2022-09-19 07:05:59,545: INFO: data_management]: data\PetImages\Cat\12235.jpg not of expected format
[2022-09-19 07:05:59,635: INFO: data_management]: data\PetImages\Cat\12269.jpg not of expected format
[2022-09-19 07:05:59,940: INFO: data_management]: data\PetImages\Cat\12370.jpg not of expected format
[2022-09-19 07:06:00,305: INFO: data_management]: data\PetImages\Cat\1267.jpg not of expected format
[2022-09-19 07:06:00,609: INFO: data_management]: data\PetImages\Cat\1386.jpg not of expected format
[2022-09-19 07:06:00,654: INFO: data_management]: data\PetImages\Cat\140.jpg not of expected format
[2022-09-19 07:06:00,798: INFO: data_management]: data\PetImages\Cat\1476.jpg not of expected format
[2022-09-19 07:06:00,813: INFO: data_management]: data\PetImages\Cat\1483.jpg not of expected format
[2022-09-19 07:06:01,323: INFO: data_management]: data\PetImages\Cat\1757.jpg not of expected format
[2022-09-19 07:06:01,446: INFO: data_management]: data\PetImages\Cat\1815.jpg not of expected format
[2022-09-19 07:06:01,645: INFO: data_management]: data\PetImages\Cat\1914.jpg not of expected format
[2022-09-19 07:06:01,678: INFO: data_management]: data\PetImages\Cat\1936.jpg not of expected format
[2022-09-19 07:06:01,683: INFO: data_management]: data\PetImages\Cat\1937.jpg not of expected format
[2022-09-19 07:06:01,835: INFO: data_management]: data\PetImages\Cat\2021.jpg not of expected format
[2022-09-19 07:06:01,996: INFO: data_management]: data\PetImages\Cat\2101.jpg not of expected format
[2022-09-19 07:06:02,253: INFO: data_management]: data\PetImages\Cat\2189.jpg not of expected format
[2022-09-19 07:06:02,752: INFO: data_management]: data\PetImages\Cat\23.jpg not of expected format
[2022-09-19 07:06:03,330: INFO: data_management]: data\PetImages\Cat\2569.jpg not of expected format
[2022-09-19 07:06:03,626: INFO: data_management]: data\PetImages\Cat\2663.jpg not of expected format
[2022-09-19 07:06:03,757: INFO: data_management]: data\PetImages\Cat\2742.jpg not of expected format
[2022-09-19 07:06:04,090: INFO: data_management]: data\PetImages\Cat\2939.jpg not of expected format
[2022-09-19 07:06:04,512: INFO: data_management]: data\PetImages\Cat\3089.jpg not of expected format
[2022-09-19 07:06:04,669: INFO: data_management]: data\PetImages\Cat\3153.jpg not of expected format
[2022-09-19 07:06:04,837: INFO: data_management]: data\PetImages\Cat\3161.jpg not of expected format
[2022-09-19 07:06:04,938: INFO: data_management]: data\PetImages\Cat\3197.jpg not of expected format
[2022-09-19 07:06:05,209: INFO: data_management]: data\PetImages\Cat\3300.jpg not of expected format
[2022-09-19 07:06:05,563: INFO: data_management]: data\PetImages\Cat\3491.jpg not of expected format
[2022-09-19 07:06:06,241: INFO: data_management]: data\PetImages\Cat\3649.jpg not of expected format
[2022-09-19 07:06:06,357: INFO: data_management]: data\PetImages\Cat\3710.jpg not of expected format
[2022-09-19 07:06:06,811: INFO: data_management]: data\PetImages\Cat\391.jpg not of expected format
[2022-09-19 07:06:07,050: INFO: data_management]: data\PetImages\Cat\3967.jpg not of expected format
[2022-09-19 07:06:07,289: INFO: data_management]: data\PetImages\Cat\4000.jpg not of expected format
[2022-09-19 07:06:07,834: INFO: data_management]: data\PetImages\Cat\4165.jpg not of expected format
[2022-09-19 07:06:08,080: INFO: data_management]: data\PetImages\Cat\4293.jpg not of expected format
[2022-09-19 07:06:08,131: INFO: data_management]: data\PetImages\Cat\4322.jpg not of expected format
[2022-09-19 07:06:08,156: INFO: data_management]: data\PetImages\Cat\4334.jpg not of expected format
[2022-09-19 07:06:08,194: INFO: data_management]: data\PetImages\Cat\4351.jpg not of expected format
[2022-09-19 07:06:08,416: INFO: data_management]: data\PetImages\Cat\445.jpg not of expected format
[2022-09-19 07:06:08,798: INFO: data_management]: data\PetImages\Cat\4629.jpg not of expected format
[2022-09-19 07:06:08,982: INFO: data_management]: data\PetImages\Cat\4750.jpg not of expected format
[2022-09-19 07:06:09,095: INFO: data_management]: data\PetImages\Cat\4821.jpg not of expected format
[2022-09-19 07:06:09,115: INFO: data_management]: data\PetImages\Cat\4833.jpg not of expected format
[2022-09-19 07:06:09,170: INFO: data_management]: data\PetImages\Cat\4874.jpg not of expected format
[2022-09-19 07:06:09,252: INFO: data_management]: data\PetImages\Cat\4929.jpg not of expected format
[2022-09-19 07:06:09,455: INFO: data_management]: data\PetImages\Cat\5077.jpg not of expected format
[2022-09-19 07:06:09,473: INFO: data_management]: data\PetImages\Cat\5089.jpg not of expected format
[2022-09-19 07:06:09,905: INFO: data_management]: data\PetImages\Cat\5370.jpg not of expected format
[2022-09-19 07:06:10,178: INFO: data_management]: data\PetImages\Cat\5553.jpg not of expected format
[2022-09-19 07:06:10,260: INFO: data_management]: data\PetImages\Cat\5614.jpg not of expected format
[2022-09-19 07:06:10,364: INFO: data_management]: data\PetImages\Cat\5686.jpg not of expected format
[2022-09-19 07:06:10,558: INFO: data_management]: data\PetImages\Cat\5819.jpg not of expected format
[2022-09-19 07:06:10,902: INFO: data_management]: data\PetImages\Cat\6029.jpg not of expected format
[2022-09-19 07:06:11,431: INFO: data_management]: data\PetImages\Cat\6376.jpg not of expected format
[2022-09-19 07:06:11,527: INFO: data_management]: data\PetImages\Cat\6435.jpg not of expected format
[2022-09-19 07:06:11,539: INFO: data_management]: data\PetImages\Cat\6438.jpg not of expected format
[2022-09-19 07:06:11,602: INFO: data_management]: data\PetImages\Cat\6486.jpg not of expected format
[2022-09-19 07:06:11,622: INFO: data_management]: data\PetImages\Cat\6491.jpg not of expected format
[2022-09-19 07:06:11,771: INFO: data_management]: data\PetImages\Cat\660.jpg not of expected format
[2022-09-19 07:06:11,849: INFO: data_management]: data\PetImages\Cat\666.jpg not of expected format
[2022-09-19 07:06:11,851: INFO: data_management]: moved bad file from data\PetImages\Cat\666.jpg to data\bad_data\666.jpg
[2022-09-19 07:06:11,852: ERROR: data_management]: cannot identify image file 'data\\PetImages\\Cat\\666.jpg'
Traceback (most recent call last):
  File "c:\users\aakas\documents\projects\computer vision\mlflow-classifire-cnn\src\utils\data_management.py", line 22, in validate_image
    img = Image.open(path_to_img)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\site-packages\PIL\Image.py", line 3148, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'data\\PetImages\\Cat\\666.jpg'
[2022-09-19 07:06:12,010: INFO: data_management]: data\PetImages\Cat\6768.jpg not of expected format
[2022-09-19 07:06:12,227: INFO: data_management]: data\PetImages\Cat\6900.jpg not of expected format
[2022-09-19 07:06:12,238: INFO: data_management]: data\PetImages\Cat\6906.jpg not of expected format
[2022-09-19 07:06:12,342: INFO: data_management]: data\PetImages\Cat\6980.jpg not of expected format
[2022-09-19 07:06:12,377: INFO: data_management]: data\PetImages\Cat\7003.jpg not of expected format
[2022-09-19 07:06:12,806: INFO: data_management]: data\PetImages\Cat\7245.jpg not of expected format
[2022-09-19 07:06:12,878: INFO: data_management]: data\PetImages\Cat\7276.jpg not of expected format
[2022-09-19 07:06:13,168: INFO: data_management]: data\PetImages\Cat\7441.jpg not of expected format
[2022-09-19 07:06:13,248: INFO: data_management]: data\PetImages\Cat\7487.jpg not of expected format
[2022-09-19 07:06:13,341: INFO: data_management]: data\PetImages\Cat\7502.jpg not of expected format
[2022-09-19 07:06:13,818: INFO: data_management]: data\PetImages\Cat\7642.jpg not of expected format
[2022-09-19 07:06:13,833: INFO: data_management]: data\PetImages\Cat\7647.jpg not of expected format
[2022-09-19 07:06:14,113: INFO: data_management]: data\PetImages\Cat\780.jpg not of expected format
[2022-09-19 07:06:14,197: INFO: data_management]: data\PetImages\Cat\7845.jpg not of expected format
[2022-09-19 07:06:14,415: INFO: data_management]: data\PetImages\Cat\7968.jpg not of expected format
[2022-09-19 07:06:14,434: INFO: data_management]: data\PetImages\Cat\7978.jpg not of expected format
[2022-09-19 07:06:14,558: INFO: data_management]: data\PetImages\Cat\8054.jpg not of expected format
[2022-09-19 07:06:14,728: INFO: data_management]: data\PetImages\Cat\8157.jpg not of expected format
[2022-09-19 07:06:14,777: INFO: data_management]: data\PetImages\Cat\8183.jpg not of expected format
[2022-09-19 07:06:14,971: INFO: data_management]: data\PetImages\Cat\8295.jpg not of expected format
[2022-09-19 07:06:15,033: INFO: data_management]: data\PetImages\Cat\8335.jpg not of expected format
[2022-09-19 07:06:15,190: INFO: data_management]: data\PetImages\Cat\8415.jpg not of expected format
[2022-09-19 07:06:15,383: INFO: data_management]: data\PetImages\Cat\8470.jpg not of expected format
[2022-09-19 07:06:15,554: INFO: data_management]: data\PetImages\Cat\850.jpg not of expected format
[2022-09-19 07:06:15,683: INFO: data_management]: data\PetImages\Cat\8553.jpg not of expected format
[2022-09-19 07:06:16,457: INFO: data_management]: data\PetImages\Cat\8832.jpg not of expected format
[2022-09-19 07:06:16,794: INFO: data_management]: data\PetImages\Cat\8958.jpg not of expected format
[2022-09-19 07:06:17,111: INFO: data_management]: data\PetImages\Cat\910.jpg not of expected format
[2022-09-19 07:06:17,132: INFO: data_management]: data\PetImages\Cat\9100.jpg not of expected format
[2022-09-19 07:06:17,349: INFO: data_management]: data\PetImages\Cat\9171.jpg not of expected format
[2022-09-19 07:06:17,434: INFO: data_management]: data\PetImages\Cat\9208.jpg not of expected format
[2022-09-19 07:06:17,533: INFO: data_management]: data\PetImages\Cat\925.jpg not of expected format
[2022-09-19 07:06:17,723: INFO: data_management]: data\PetImages\Cat\9328.jpg not of expected format
[2022-09-19 07:06:17,795: INFO: data_management]: data\PetImages\Cat\936.jpg not of expected format
[2022-09-19 07:06:17,804: INFO: data_management]: data\PetImages\Cat\9361.jpg not of expected format
[2022-09-19 07:06:18,417: INFO: data_management]: data\PetImages\Cat\9565.jpg not of expected format
[2022-09-19 07:06:18,563: INFO: data_management]: data\PetImages\Cat\9619.jpg not of expected format
[2022-09-19 07:06:18,898: INFO: data_management]: data\PetImages\Cat\9778.jpg not of expected format
[2022-09-19 07:06:19,399: INFO: data_management]: data\PetImages\Cat\Thumbs.db not of expected format
[2022-09-19 07:06:19,405: INFO: data_management]: moved bad file from data\PetImages\Cat\Thumbs.db to data\bad_data\Thumbs.db
[2022-09-19 07:06:19,405: ERROR: data_management]: cannot identify image file 'data\\PetImages\\Cat\\Thumbs.db'
Traceback (most recent call last):
  File "c:\users\aakas\documents\projects\computer vision\mlflow-classifire-cnn\src\utils\data_management.py", line 22, in validate_image
    img = Image.open(path_to_img)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\site-packages\PIL\Image.py", line 3148, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'data\\PetImages\\Cat\\Thumbs.db'
[2022-09-19 07:06:19,715: INFO: data_management]: data\PetImages\Dog\10158.jpg not of expected format
[2022-09-19 07:06:19,741: INFO: data_management]: data\PetImages\Dog\10163.jpg not of expected format
[2022-09-19 07:06:19,757: INFO: data_management]: data\PetImages\Dog\1017.jpg not of expected format
[2022-09-19 07:06:19,768: INFO: data_management]: data\PetImages\Dog\10173.jpg not of expected format
[2022-09-19 07:06:20,084: INFO: data_management]: data\PetImages\Dog\10351.jpg not of expected format
[2022-09-19 07:06:20,091: INFO: data_management]: data\PetImages\Dog\10353.jpg not of expected format
[2022-09-19 07:06:20,150: INFO: data_management]: data\PetImages\Dog\10383.jpg not of expected format
[2022-09-19 07:06:20,179: INFO: data_management]: data\PetImages\Dog\10401.jpg not of expected format
[2022-09-19 07:06:20,532: INFO: data_management]: data\PetImages\Dog\10637.jpg not of expected format
[2022-09-19 07:06:20,592: INFO: data_management]: data\PetImages\Dog\10678.jpg not of expected format
[2022-09-19 07:06:20,629: INFO: data_management]: data\PetImages\Dog\10705.jpg not of expected format
[2022-09-19 07:06:20,658: INFO: data_management]: data\PetImages\Dog\10726.jpg not of expected format
[2022-09-19 07:06:20,670: INFO: data_management]: data\PetImages\Dog\10733.jpg not of expected format
[2022-09-19 07:06:20,688: INFO: data_management]: data\PetImages\Dog\10745.jpg not of expected format
[2022-09-19 07:06:20,693: INFO: data_management]: data\PetImages\Dog\10747.jpg not of expected format
[2022-09-19 07:06:20,761: INFO: data_management]: data\PetImages\Dog\10797.jpg not of expected format
[2022-09-19 07:06:20,879: INFO: data_management]: data\PetImages\Dog\10863.jpg not of expected format
[2022-09-19 07:06:20,966: INFO: data_management]: data\PetImages\Dog\10907.jpg not of expected format
[2022-09-19 07:06:21,035: INFO: data_management]: data\PetImages\Dog\10949.jpg not of expected format
[2022-09-19 07:06:21,073: INFO: data_management]: data\PetImages\Dog\10969.jpg not of expected format
[2022-09-19 07:06:21,082: INFO: data_management]: data\PetImages\Dog\10972.jpg not of expected format
[2022-09-19 07:06:21,368: INFO: data_management]: data\PetImages\Dog\11166.jpg not of expected format
[2022-09-19 07:06:21,376: INFO: data_management]: data\PetImages\Dog\1117.jpg not of expected format
[2022-09-19 07:06:21,486: INFO: data_management]: data\PetImages\Dog\11233.jpg not of expected format
[2022-09-19 07:06:21,521: INFO: data_management]: data\PetImages\Dog\11253.jpg not of expected format
[2022-09-19 07:06:21,584: INFO: data_management]: data\PetImages\Dog\11285.jpg not of expected format
[2022-09-19 07:06:21,760: INFO: data_management]: data\PetImages\Dog\11410.jpg not of expected format
[2022-09-19 07:06:21,978: INFO: data_management]: data\PetImages\Dog\11560.jpg not of expected format
[2022-09-19 07:06:22,032: INFO: data_management]: data\PetImages\Dog\11590.jpg not of expected format
[2022-09-19 07:06:22,191: INFO: data_management]: data\PetImages\Dog\11675.jpg not of expected format
[2022-09-19 07:06:22,202: INFO: data_management]: data\PetImages\Dog\1168.jpg not of expected format
[2022-09-19 07:06:22,223: INFO: data_management]: data\PetImages\Dog\11692.jpg not of expected format
[2022-09-19 07:06:22,235: INFO: data_management]: data\PetImages\Dog\11702.jpg not of expected format
[2022-09-19 07:06:22,238: INFO: data_management]: moved bad file from data\PetImages\Dog\11702.jpg to data\bad_data\11702.jpg
[2022-09-19 07:06:22,238: ERROR: data_management]: cannot identify image file 'data\\PetImages\\Dog\\11702.jpg'
Traceback (most recent call last):
  File "c:\users\aakas\documents\projects\computer vision\mlflow-classifire-cnn\src\utils\data_management.py", line 22, in validate_image
    img = Image.open(path_to_img)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\site-packages\PIL\Image.py", line 3148, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'data\\PetImages\\Dog\\11702.jpg'
[2022-09-19 07:06:22,426: INFO: data_management]: data\PetImages\Dog\11849.jpg not of expected format
[2022-09-19 07:06:22,435: INFO: data_management]: data\PetImages\Dog\11853.jpg not of expected format
[2022-09-19 07:06:22,517: INFO: data_management]: data\PetImages\Dog\11912.jpg not of expected format
[2022-09-19 07:06:22,850: INFO: data_management]: data\PetImages\Dog\12102.jpg not of expected format
[2022-09-19 07:06:22,875: INFO: data_management]: data\PetImages\Dog\12114.jpg not of expected format
[2022-09-19 07:06:23,156: INFO: data_management]: data\PetImages\Dog\12289.jpg not of expected format
[2022-09-19 07:06:23,593: INFO: data_management]: data\PetImages\Dog\1259.jpg not of expected format
[2022-09-19 07:06:23,680: INFO: data_management]: data\PetImages\Dog\1308.jpg not of expected format
[2022-09-19 07:06:23,755: INFO: data_management]: data\PetImages\Dog\1356.jpg not of expected format
[2022-09-19 07:06:24,387: INFO: data_management]: data\PetImages\Dog\1773.jpg not of expected format
[2022-09-19 07:06:24,412: INFO: data_management]: data\PetImages\Dog\1789.jpg not of expected format
[2022-09-19 07:06:24,516: INFO: data_management]: data\PetImages\Dog\1866.jpg not of expected format
[2022-09-19 07:06:24,547: INFO: data_management]: data\PetImages\Dog\1884.jpg not of expected format
[2022-09-19 07:06:24,573: INFO: data_management]: data\PetImages\Dog\1900.jpg not of expected format
[2022-09-19 07:06:25,179: INFO: data_management]: data\PetImages\Dog\2317.jpg not of expected format
[2022-09-19 07:06:25,210: INFO: data_management]: data\PetImages\Dog\2339.jpg not of expected format
[2022-09-19 07:06:25,232: INFO: data_management]: data\PetImages\Dog\2353.jpg not of expected format
[2022-09-19 07:06:25,274: INFO: data_management]: data\PetImages\Dog\2384.jpg not of expected format
[2022-09-19 07:06:25,405: INFO: data_management]: data\PetImages\Dog\2479.jpg not of expected format
[2022-09-19 07:06:25,430: INFO: data_management]: data\PetImages\Dog\2494.jpg not of expected format
[2022-09-19 07:06:25,698: INFO: data_management]: data\PetImages\Dog\2688.jpg not of expected format
[2022-09-19 07:06:25,978: INFO: data_management]: data\PetImages\Dog\2877.jpg not of expected format
[2022-09-19 07:06:26,020: INFO: data_management]: data\PetImages\Dog\2905.jpg not of expected format
[2022-09-19 07:06:26,037: INFO: data_management]: data\PetImages\Dog\2915.jpg not of expected format
[2022-09-19 07:06:26,088: INFO: data_management]: data\PetImages\Dog\296.jpg not of expected format
[2022-09-19 07:06:26,169: INFO: data_management]: data\PetImages\Dog\3038.jpg not of expected format
[2022-09-19 07:06:26,269: INFO: data_management]: data\PetImages\Dog\3136.jpg not of expected format
[2022-09-19 07:06:26,286: INFO: data_management]: data\PetImages\Dog\3155.jpg not of expected format
[2022-09-19 07:06:26,375: INFO: data_management]: data\PetImages\Dog\3252.jpg not of expected format
[2022-09-19 07:06:26,410: INFO: data_management]: data\PetImages\Dog\3288.jpg not of expected format
[2022-09-19 07:06:26,439: INFO: data_management]: data\PetImages\Dog\3320.jpg not of expected format
[2022-09-19 07:06:26,643: INFO: data_management]: data\PetImages\Dog\3546.jpg not of expected format
[2022-09-19 07:06:26,687: INFO: data_management]: data\PetImages\Dog\3588.jpg not of expected format
[2022-09-19 07:06:26,960: INFO: data_management]: data\PetImages\Dog\3823.jpg not of expected format
[2022-09-19 07:06:27,020: INFO: data_management]: data\PetImages\Dog\3885.jpg not of expected format
[2022-09-19 07:06:27,062: INFO: data_management]: data\PetImages\Dog\3927.jpg not of expected format
[2022-09-19 07:06:27,197: INFO: data_management]: data\PetImages\Dog\4086.jpg not of expected format
[2022-09-19 07:06:27,236: INFO: data_management]: data\PetImages\Dog\4134.jpg not of expected format
[2022-09-19 07:06:27,244: INFO: data_management]: data\PetImages\Dog\414.jpg not of expected format
[2022-09-19 07:06:27,326: INFO: data_management]: data\PetImages\Dog\4203.jpg not of expected format
[2022-09-19 07:06:27,384: INFO: data_management]: data\PetImages\Dog\4257.jpg not of expected format
[2022-09-19 07:06:27,436: INFO: data_management]: data\PetImages\Dog\4301.jpg not of expected format
[2022-09-19 07:06:27,492: INFO: data_management]: data\PetImages\Dog\4367.jpg not of expected format
[2022-09-19 07:06:27,660: INFO: data_management]: data\PetImages\Dog\4515.jpg not of expected format
[2022-09-19 07:06:27,791: INFO: data_management]: data\PetImages\Dog\4640.jpg not of expected format
[2022-09-19 07:06:27,809: INFO: data_management]: data\PetImages\Dog\4654.jpg not of expected format
[2022-09-19 07:06:28,282: INFO: data_management]: data\PetImages\Dog\4855.jpg not of expected format
[2022-09-19 07:06:28,423: INFO: data_management]: data\PetImages\Dog\4924.jpg not of expected format
[2022-09-19 07:06:28,637: INFO: data_management]: data\PetImages\Dog\50.jpg not of expected format
[2022-09-19 07:06:28,788: INFO: data_management]: data\PetImages\Dog\5104.jpg not of expected format
[2022-09-19 07:06:28,886: INFO: data_management]: data\PetImages\Dog\522.jpg not of expected format
[2022-09-19 07:06:28,904: INFO: data_management]: data\PetImages\Dog\5243.jpg not of expected format
[2022-09-19 07:06:28,923: INFO: data_management]: data\PetImages\Dog\5263.jpg not of expected format
[2022-09-19 07:06:29,084: INFO: data_management]: data\PetImages\Dog\543.jpg not of expected format
[2022-09-19 07:06:29,215: INFO: data_management]: data\PetImages\Dog\5547.jpg not of expected format
[2022-09-19 07:06:29,274: INFO: data_management]: data\PetImages\Dog\5604.jpg not of expected format
[2022-09-19 07:06:29,282: INFO: data_management]: data\PetImages\Dog\561.jpg not of expected format
[2022-09-19 07:06:29,296: INFO: data_management]: data\PetImages\Dog\5618.jpg not of expected format
[2022-09-19 07:06:29,336: INFO: data_management]: data\PetImages\Dog\565.jpg not of expected format
[2022-09-19 07:06:29,441: INFO: data_management]: data\PetImages\Dog\573.jpg not of expected format
[2022-09-19 07:06:29,446: INFO: data_management]: data\PetImages\Dog\5730.jpg not of expected format
[2022-09-19 07:06:29,455: INFO: data_management]: data\PetImages\Dog\5736.jpg not of expected format
[2022-09-19 07:06:29,527: INFO: data_management]: data\PetImages\Dog\5790.jpg not of expected format
[2022-09-19 07:06:29,541: INFO: data_management]: data\PetImages\Dog\5797.jpg not of expected format
[2022-09-19 07:06:29,691: INFO: data_management]: data\PetImages\Dog\5955.jpg not of expected format
[2022-09-19 07:06:29,773: INFO: data_management]: data\PetImages\Dog\6032.jpg not of expected format
[2022-09-19 07:06:29,801: INFO: data_management]: data\PetImages\Dog\6059.jpg not of expected format
[2022-09-19 07:06:29,829: INFO: data_management]: data\PetImages\Dog\6086.jpg not of expected format
[2022-09-19 07:06:29,942: INFO: data_management]: data\PetImages\Dog\6213.jpg not of expected format
[2022-09-19 07:06:29,967: INFO: data_management]: data\PetImages\Dog\6238.jpg not of expected format
[2022-09-19 07:06:29,978: INFO: data_management]: data\PetImages\Dog\6245.jpg not of expected format
[2022-09-19 07:06:30,040: INFO: data_management]: data\PetImages\Dog\6305.jpg not of expected format
[2022-09-19 07:06:30,059: INFO: data_management]: data\PetImages\Dog\6318.jpg not of expected format
[2022-09-19 07:06:30,175: INFO: data_management]: data\PetImages\Dog\6430.jpg not of expected format
[2022-09-19 07:06:30,248: INFO: data_management]: data\PetImages\Dog\6500.jpg not of expected format
[2022-09-19 07:06:30,258: INFO: data_management]: data\PetImages\Dog\6503.jpg not of expected format
[2022-09-19 07:06:30,377: INFO: data_management]: data\PetImages\Dog\6555.jpg not of expected format
[2022-09-19 07:06:30,695: INFO: data_management]: data\PetImages\Dog\663.jpg not of expected format
[2022-09-19 07:06:30,851: INFO: data_management]: data\PetImages\Dog\6718.jpg not of expected format
[2022-09-19 07:06:31,118: INFO: data_management]: data\PetImages\Dog\6855.jpg not of expected format
[2022-09-19 07:06:31,172: INFO: data_management]: data\PetImages\Dog\6904.jpg not of expected format
[2022-09-19 07:06:31,359: INFO: data_management]: data\PetImages\Dog\7083.jpg not of expected format
[2022-09-19 07:06:31,397: INFO: data_management]: data\PetImages\Dog\7112.jpg not of expected format
[2022-09-19 07:06:31,411: INFO: data_management]: data\PetImages\Dog\7128.jpg not of expected format
[2022-09-19 07:06:31,420: INFO: data_management]: data\PetImages\Dog\7133.jpg not of expected format
[2022-09-19 07:06:31,472: INFO: data_management]: data\PetImages\Dog\719.jpg not of expected format
[2022-09-19 07:06:31,601: INFO: data_management]: data\PetImages\Dog\7311.jpg not of expected format
[2022-09-19 07:06:31,664: INFO: data_management]: data\PetImages\Dog\7369.jpg not of expected format
[2022-09-19 07:06:31,752: INFO: data_management]: data\PetImages\Dog\7459.jpg not of expected format
[2022-09-19 07:06:31,792: INFO: data_management]: data\PetImages\Dog\7496.jpg not of expected format
[2022-09-19 07:06:31,810: INFO: data_management]: data\PetImages\Dog\7514.jpg not of expected format
[2022-09-19 07:06:31,929: INFO: data_management]: data\PetImages\Dog\7652.jpg not of expected format
[2022-09-19 07:06:31,992: INFO: data_management]: data\PetImages\Dog\7718.jpg not of expected format
[2022-09-19 07:06:32,005: INFO: data_management]: data\PetImages\Dog\7729.jpg not of expected format
[2022-09-19 07:06:32,014: INFO: data_management]: data\PetImages\Dog\7739.jpg not of expected format
[2022-09-19 07:06:32,021: INFO: data_management]: data\PetImages\Dog\7743.jpg not of expected format
[2022-09-19 07:06:32,237: INFO: data_management]: data\PetImages\Dog\7969.jpg not of expected format
[2022-09-19 07:06:32,269: INFO: data_management]: data\PetImages\Dog\7989.jpg not of expected format
[2022-09-19 07:06:32,377: INFO: data_management]: data\PetImages\Dog\8126.jpg not of expected format
[2022-09-19 07:06:32,427: INFO: data_management]: data\PetImages\Dog\8194.jpg not of expected format
[2022-09-19 07:06:32,583: INFO: data_management]: data\PetImages\Dog\8364.jpg not of expected format
[2022-09-19 07:06:32,783: INFO: data_management]: data\PetImages\Dog\8521.jpg not of expected format
[2022-09-19 07:06:32,825: INFO: data_management]: data\PetImages\Dog\8557.jpg not of expected format
[2022-09-19 07:06:32,840: INFO: data_management]: data\PetImages\Dog\8563.jpg not of expected format
[2022-09-19 07:06:33,150: INFO: data_management]: data\PetImages\Dog\8641.jpg not of expected format
[2022-09-19 07:06:33,278: INFO: data_management]: data\PetImages\Dog\8693.jpg not of expected format
[2022-09-19 07:06:33,376: INFO: data_management]: data\PetImages\Dog\8715.jpg not of expected format
[2022-09-19 07:06:33,440: INFO: data_management]: data\PetImages\Dog\8730.jpg not of expected format
[2022-09-19 07:06:33,745: INFO: data_management]: data\PetImages\Dog\9026.jpg not of expected format
[2022-09-19 07:06:33,782: INFO: data_management]: data\PetImages\Dog\9043.jpg not of expected format
[2022-09-19 07:06:33,875: INFO: data_management]: data\PetImages\Dog\9078.jpg not of expected format
[2022-09-19 07:06:33,958: INFO: data_management]: data\PetImages\Dog\9145.jpg not of expected format
[2022-09-19 07:06:33,996: INFO: data_management]: data\PetImages\Dog\9188.jpg not of expected format
[2022-09-19 07:06:34,182: INFO: data_management]: data\PetImages\Dog\9367.jpg not of expected format
[2022-09-19 07:06:34,229: INFO: data_management]: data\PetImages\Dog\9414.jpg not of expected format
[2022-09-19 07:06:34,301: INFO: data_management]: data\PetImages\Dog\9500.jpg not of expected format
[2022-09-19 07:06:34,343: INFO: data_management]: data\PetImages\Dog\9556.jpg not of expected format
[2022-09-19 07:06:34,430: INFO: data_management]: data\PetImages\Dog\9640.jpg not of expected format
[2022-09-19 07:06:34,437: INFO: data_management]: data\PetImages\Dog\9643.jpg not of expected format
[2022-09-19 07:06:34,695: INFO: data_management]: data\PetImages\Dog\9851.jpg not of expected format
[2022-09-19 07:06:34,781: INFO: data_management]: data\PetImages\Dog\9961.jpg not of expected format
[2022-09-19 07:06:34,792: INFO: data_management]: data\PetImages\Dog\9967.jpg not of expected format
[2022-09-19 07:06:34,826: INFO: data_management]: data\PetImages\Dog\Thumbs.db not of expected format
[2022-09-19 07:06:34,870: INFO: data_management]: moved bad file from data\PetImages\Dog\Thumbs.db to data\bad_data\Thumbs.db
[2022-09-19 07:06:34,870: ERROR: data_management]: cannot identify image file 'data\\PetImages\\Dog\\Thumbs.db'
Traceback (most recent call last):
  File "c:\users\aakas\documents\projects\computer vision\mlflow-classifire-cnn\src\utils\data_management.py", line 22, in validate_image
    img = Image.open(path_to_img)
  File "C:\Users\aakas\Documents\projects\computer vision\MLflow-classifire-CNN\env\lib\site-packages\PIL\Image.py", line 3148, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'data\\PetImages\\Dog\\Thumbs.db'
[2022-09-19 07:06:34,870: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

